# Generated by Django 4.2.2 on 2023-06-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('summary', models.TextField(default='', max_length=1000)),
                ('short_description', models.CharField(default='', max_length=2000)),
                ('long_description', models.TextField(default='', max_length=10000)),
                ('featured_img', models.URLField(default='', max_length=5000)),
                ('screenshot', models.URLField(default='', max_length=5000)),
                ('live_link', models.URLField(default='', max_length=1000)),
            ],
        ),
    ]
