# Generated by Django 4.2.2 on 2023-06-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.ManyToManyField(to='portfolio_app.feature'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='portfolio_app.technology'),
        ),
    ]
