# Generated by Django 4.2.2 on 2023-06-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_alter_project_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.CharField(choices=[('Authentication, Admin, Email Service, Notifier, Search Filter, Lazy Loading, Error Handling, Form Validation', 'Authentication, Admin, Email Service, Notifier, Search Filter, Lazy Loading, Error Handling, Form Validation'), ('Admin, Email Service, Notifier, Search Filter, Lazy Loading, Error Handling, Form Validation', 'Admin, Email Service, Notifier, Search Filter, Lazy Loading, Error Handling, Form Validation'), ('Authentication, Email Service, Notifier, Error Handling, Form Validation', 'Authentication, Email Service, Notifier, Error Handling, Form Validation'), ('Email Service, Notifier, Search Filter, Error Handling, Form Validation', 'Email Service, Notifier, Search Filter, Error Handling, Form Validation'), ('Email Service, Notifier, Error Handling, Form Validation', 'Email Service, Notifier, Error Handling, Form Validation')], default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(choices=[('Django, Angular, SQL, DRF, Railway, Firebase', 'Django, Angular, SQL, DRF, Railway, Firebase'), ('Django, Angular, SQL, DRF, Vercel, Firebase', 'Django, Angular, SQL, DRF, Vercel, Firebase')], default='', max_length=1000),
        ),
    ]
