# Generated by Django 4.2.2 on 2023-06-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_remove_project_features_remove_project_technologies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_link',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
