# Generated by Django 4.2.2 on 2023-06-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0016_remove_project_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot_2',
            field=models.URLField(default='', max_length=5000),
        ),
    ]
