# Generated by Django 4.2.2 on 2023-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0017_project_screenshot_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.URLField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot_2',
            field=models.URLField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
