# Generated by Django 4.2.2 on 2023-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0018_alter_project_screenshot_alter_project_screenshot_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.CharField(choices=[('Authentication, Admin, Email Service, Notifier, Search Filter, Lazy Loading, Error Handling, Form Validation', 'Authentication, Admin, Email Service, Notifier, Search Filter, Lazy Loading, Error Handling, Form Validation'), ('Admin, Email Service, Notifier, Search Filter, Lazy Loading, Error Handling, Form Validation', 'Admin, Email Service, Notifier, Search Filter, Lazy Loading, Error Handling, Form Validation'), ('Authentication, Email Service, SMS Service, Notifier, Error Handling, Form Validation', 'Authentication, Email Service, SMS Service, Notifier, Error Handling, Form Validation'), ('Authentication, Email Service, Notifier, Error Handling, Form Validation', 'Authentication, Email Service, Notifier, Error Handling, Form Validation'), ('Email Service, Notifier, Search Filter, Error Handling, Form Validation', 'Email Service, Notifier, Search Filter, Error Handling, Form Validation'), ('Email Service, Notifier, Error Handling, Form Validation', 'Email Service, Notifier, Error Handling, Form Validation'), ('Custom Authentication, API, Email Service', 'Custom Authentication, API, Email Service'), ('Custom Authentication, API, Email Service, SMS Service', 'Custom Authentication, API, Email Service, SMS Service'), ('API, Email Service, SMS Service', 'API, Email Service, SMS Service'), ('API, Email Service', 'API, Email Service'), ('API', 'API')], default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(choices=[('Django, Angular, SQL, DRF, Firebase, Railway', 'Django, Angular, SQL, DRF, Firebase, Railway'), ('Django, Angular, SQL, DRF, Firebase, Vercel', 'Django, Angular, SQL, DRF, Firebase, Vercel'), ('Django, SQL, DRF, Railway', 'Django, SQL, DRF, Railway'), ('Django, SQL, DRF, Vercel', 'Django, SQL, DRF, Vercel')], default='', max_length=1000),
        ),
    ]
