# Generated by Django 4.2.2 on 2023-06-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0019_alter_project_features_alter_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.CharField(choices=[('featured', 'featured'), ('not featured', 'not featured')], default='', max_length=500),
        ),
    ]
